### ISSUE TITLE
Pretty URLs.

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#109]
I think we should for convenience hook up https://matrixvoip.dev/Foo to point to #Foo:matrixvoip.dev, and do the same trick as Jitsi for autocreating rooms if you make up a URL that points to an alias that doesn't exist.

We'd then also support https://matrixvoip.dev/#/#wherever:matrix.org to refer to remote aliases as normal, or https://matrixvoip.dev/#/!qiuydsfcgywu21:matrix.org?matrix.org for rooms without aliases.

**Comment by lampholder** [comment]
This experience differs from Jitsi in an important way. Jitsi's ephemeral meeting URIs encourages reuse, and the ability to reuse means that the experience remains light and quick and easy.

I wonder if the approach outlined above will:
- tend towards all the simple aliases being associated with pre-existing rooms (with the clashes meaning the rooms are inaccessible, resulting in either people losing faith in the setupless meeting flow, or always generating meeting ids with human-random suffixes /MeetingSDFSDFSDFSDF23894)
- result in a build up of ghost Matrix rooms, filled with join and VoIP events that leave a trail of who was talking to whom and when (this is not something we have to worry about with Jitsi today)

**Comment by robertlong** [comment]
We now support these short urls in the app. However, @lampholder has a good call out here. We should be weary of room history for these public rooms. Random room name generation, improved permissions, etc. seem like next steps for the product. Privacy/security through obscurity with user-input room names doesn't really work.
