### ISSUE TITLE
Cancelling a screenshare doesn’t hang up the screenshare

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#116]
If you're screensharing and hit the "stop share" button provided by the browser, it doesn't cancel the screenshare unless you also kill the screenshare button in the app.

**Comment by robertlong** [comment]
Fixed in https://github.com/matrix-org/matrix-js-sdk/commit/64c3ac55a43eaa5f0cf7bec2324e05930b09a41f
