### ISSUE TITLE
Sound in Firefox only works through the left channel

### ISSUE THREAD

**Issue by foxlet** [vector-im/matrix-video-chat#117]
**Describe the bug**
When making a call from a Firefox user to one or more Firefox users, sound can only be heard on the left channel. Firefox Mic -> Chrome works in stereo, and Chrome Mic -> Firefox is also in stereo. Chrome -> Chrome is unaffected.

**To Reproduce**
1. Open a video room in Firefox
2. Listen and talk to other users

**Desktop (please complete the following information):**
 - OS: Void Linux
 - Firefox 93.0 (64-bit)

**Comment by robertlong** [comment]
Hmm, Idk that I can reproduce this on my end. Can you give a little more detail on your set up? What devices are involved? What browser is used on each device?

**Comment by foxlet** [comment]
> Hmm, Idk that I can reproduce this on my end. Can you give a little more detail on your set up? What devices are involved? What browser is used on each device?

They are all desktop PCs running Firefox 93, two of the machines use an identical XLR Mic + USB DAC combo, while the third uses a mono microphone connected to the audio card.

**Comment by foxlet** [comment]
I've tried reproducing this more recently with the same setup, and was unable to find the issue again, so perhaps it can be marked as fixed.

**Comment by robertlong** [comment]
Ok, thanks @foxlet!
