### ISSUE TITLE
User Avatars

### ISSUE THREAD

**Issue by robertlong** [vector-im/matrix-video-chat#12]
You should be able to set/change your user avatar in the conference UI. The avatars should be shown when your webcam is disabled or if you are using audio only.

**Comment by SimonBrandner** [comment]
> The avatars should be shown when your webcam is disabled or if you are using audio only.

Should be super straightforward with https://github.com/matrix-org/matrix-doc/pull/3291 which is now fully implemented in the js-sdk

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/1ab7d27ba9560a100b0b984682ff0ed76cbe12ff
