### ISSUE TITLE
Tooltips on camera icon are inverted

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#132]
The tooltops on the camera icon are inverted. 
- When camera is on, the tooltip reads 'turn on camera'
- When camera is off, the tooltip reads 'turn off camer
![Screenshot 2021-12-06 at 11 08 18](https://user-images.githubusercontent.com/87766619/144835990-424606da-9a6b-4403-91d2-e483032de4ad.png)
![Screenshot 2021-12-06 at 11 08 23](https://user-images.githubusercontent.com/87766619/144836000-a60aa6a0-c0c2-4ff3-b480-53ff80e81ff8.png)
a'

**Comment by robertlong** [comment]
This is now fixed on staging
