### ISSUE TITLE
Polish home screen

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#133]
For best first-time user experience, we need a slightly more polished home screen for the beta release.

Figma link here https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/VoIP-Next-Gen?node-id=929%3A87745

But even if we can't fully implement every detail of this design by this month's release, as a minimum could we have:

- The name of the product at the top left next to the logo
- A nicer username display and log-out at top right
- Divide the interactions into 'create' and 'join'. Including the warning when creating a room that already exists ("This room already exists, would you like to join instead?" With Join button).

**Comment by robertlong** [comment]
I've pushed these changes to staging. Going through a polish pass with Gaelle now
