### ISSUE TITLE
Incoming audio from other users is choppy/stuttery under Firefox

### ISSUE THREAD

**Issue by foxlet** [vector-im/matrix-video-chat#134]
**Describe the bug**
When in a call with other Firefox users, incoming audio plays back with major stutters or with silence, this occurs throughout the duration of the conference call.

**To Reproduce**
1. Join a room under Firefox
2. Listen to incoming audio

**Expected behavior**
Clean audio without cuts or stutters.

**Screenshots**
A sound recording is available on request.

**Desktop (please complete the following information):**
 - OS: Void Linux glibc
 - Firefox 93.0 (64-bit)
 - Analog shotgun mic (built-in HD audio)

**Additional context**
This occurred over the past few days after the issue with left-channel sound disappeared.

**Comment by robertlong** [comment]
Merging with #199
