### ISSUE TITLE
Home screen - I cannot scroll the join/create call side of the screen meaning that the bottom part is inaccessible on smaller screen sizes

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#135]
On MacBook Pro (13-inch, M1, 2020), on built-in retina display, the create a call button and 'guest access' checkbox are hidden off the bottom of the screen, and I cannot scroll this part of the window so I cannot access them. 
<img width="754" alt="Screenshot 2021-12-08 at 09 39 49" src="https://user-images.githubusercontent.com/87766619/145193388-e28068c6-f908-46bf-9611-ba1c0b14d693.png">

**Comment by robertlong** [comment]
This is now fixed on staging
