### ISSUE TITLE
UI modifications - Lobby

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#138]
- [x] On the Lobby screens, remove the back button for all user types. We however, preserve the Take me Home button at the bottom of the UI.

- [x] The content of the screen need to be moved upwards so I don't need to scroll to see the content at the bottom. (on default browser sizes)

- [x] The title of the call (above the video feed) should refer to the state of the call. For example if it is a new call created then it should be the string "New call". If the call already exists then the string should be replaced with the name of the meeting.
<img width="719" alt="Screenshot 2021-12-13 at 15 20 12" src="https://user-images.githubusercontent.com/76945183/145838759-3f8ad03d-21c3-4ea9-baa0-4530ae1cb8f8.png">

- [x] The Join call now button needs to be more prominent for users. Its size needs enlarged a bit so the core action is emphasised.

- [x] The background of the call controls needs to be changed to System dark #21262C

- [x] On click call control, we shouldn't change its colour. Its colour should return to default colour (System dark) when users click.
<img width="338" alt="Screenshot 2021-12-13 at 15 22 31" src="https://user-images.githubusercontent.com/76945183/145839096-810a6c28-a134-4e22-87c2-cffbb4f62abb.png">

- [x] The drop down Hover colour needs to be changed as stated in the Home UI modif ticket.

- [x] For when users click on "copy call link and join later) the active state should show the string " Call link copied" with a check mark.
<img width="506" alt="Screenshot 2021-12-13 at 15 37 44" src="https://user-images.githubusercontent.com/76945183/145841680-feb0e8a9-86f0-4213-8485-8f873ac3fc92.png">

- [x] Settings Modal: The drop down field open state need to be tweaked. I have added specs in Figma here https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=845%3A82396

- [x] Settings Modal: The Left nav panel strings when not selected seem too dark and it'll create accessibility issues. Need to change to "Dark secondary": #A9B2BC

- [x] For Anonymous guests, we should display a "Log in" button at the right hand corner of the UI
<img width="686" alt="Screenshot 2021-12-13 at 15 42 44" src="https://user-images.githubusercontent.com/76945183/145842702-7973dec9-11ed-4df2-9645-d8c1271f0421.png">

- [ ] For logged in users, we should display their avatar with the ability for them to change their display name and to log out.

- [x] The "Take me Home" Text button should be unbolded

**Comment by robertlong** [comment]
> The title of the call (above the video feed) should refer to the state of the call. For example if it is a new call created then it should be the string "New call". If the call already exists then the string should be replaced with the name of the meeting.

I think we always have the name of the room, so I think we can always render it here.

**Comment by robertlong** [comment]
Changing display name is implemented and I'll track user avatars here: https://github.com/vector-im/matrix-video-chat/issues/12
