### ISSUE TITLE
UI modifications - In Call Screen

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#139]
- [x] The colour of the icons in the nav need to be changed on default state to Primary

- [x] On the invite people modal, can we display the string "call link copied" plus check icon. Weirdly, the modal changes size as I click on the button. Ideally the size of the modal should be set  to one size  and similarly for the 2 button states

- [x] On click on the user profile ( guest) we should allow users to change their display name 
<img width="686" alt="Screenshot 2021-12-13 at 16 03 36" src="https://user-images.githubusercontent.com/76945183/145846205-1b6cdb13-6d79-4d2b-92f7-b2486ec59161.png">

- [ ] #154

https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=1083%3A48091

Ending a call:

- [x] For Guests and Anonymous users we should show the "your call is now ended" screen
<img width="793" alt="Screenshot 2021-12-13 at 16 05 14" src="https://user-images.githubusercontent.com/76945183/145846448-c3cf1ddf-72f1-4a1b-a48f-054412a60e6c.png">

- [x] For logged in users, we should redirect them to their Home screen.

**Comment by robertlong** [comment]
>  For Guests and Anonymous users we should show the "your call is now ended" screen

For passwordless users, I think this copy needs to change to tell them to set a password, not create an account.

**Comment by gaelledel** [comment]
Yes I agree. @jakewb-b will be helping us with copy for PW less users and Anon guests.

**Comment by gaelledel** [comment]
@robertlong 
**For PWL guest users:**
We're calling the name of the guest e.g: "Jake, your call is now ended, Why not finish by setting up a password to keep your account? etc..." This is followed by a "Create account" button which then leads to a create account screen with the username field pre populated with "Jake"
https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=1147%3A43787

**For Anon guests:**
"Your call is now ended, Why not finish by creating an account?" etc... This is followed by a Create an account button leading to the default Create account page"
https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=798%3A78398

**Comment by robertlong** [comment]
Cool, I've adjusted that copy and split out the remaining avatar related ticket. Closing this now
