### ISSUE TITLE
Review copy for the "your call is now ended screen" (Guests and anonymous)

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#140]
@jakewb-b 

<img width="839" alt="Screenshot 2021-12-13 at 16 07 57" src="https://user-images.githubusercontent.com/76945183/145846868-3932c700-a98e-4248-92d9-be7ca19685e0.png">

https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=798%3A78398

**Comment by robertlong** [comment]
I've updated to the latest copy
