### ISSUE TITLE
Add/Edit Error screen

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#141]
<img width="519" alt="Screenshot 2021-12-13 at 16 09 48" src="https://user-images.githubusercontent.com/76945183/145847159-14ea4b23-6926-46c9-8d1f-62737ab9d606.png">

https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=798%3A78418

**Comment by robertlong** [comment]
This is live on staging
