### ISSUE TITLE
Lobby Anonymous

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#143]
Just in case this slipped my mind, On Lobby for Anonymous users, we want to allow them to log in
<img width="1920" alt="Screenshot 2021-12-14 at 10 28 52 (2)" src="https://user-images.githubusercontent.com/76945183/145981202-af2bb49c-a629-4d03-bd93-431a300aba7a.png">

https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=929%3A90623

**Comment by robertlong** [comment]
This should be finished now
