### ISSUE TITLE
Add the user's name on the drop down

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#147]
For both PWless users and Logged in users, can we add their name in the drop down?

See below:
<img width="714" alt="Screenshot 2021-12-15 at 12 05 14" src="https://user-images.githubusercontent.com/76945183/146183758-ef919560-1420-43c3-b113-c11e479f2992.png">

<img width="592" alt="Screenshot 2021-12-15 at 12 04 36" src="https://user-images.githubusercontent.com/76945183/146183777-77d0c0c9-006a-4ade-9bea-981e6cd7e9ed.png">

**Comment by robertlong** [comment]
This should already be live on staging. Not matrixvoip.dev yet but I'll get that out now
