### ISSUE TITLE
Screenshare is incorrectly horizontally flipped

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#148]
I just joined a room by myself and shared my screen.  The screenshare was shown flipped horizontally.  Instead, I'd expect only local video (not local screenshare) to be shown flipped as if in a mirror.

(My local video was also shown in the corner of the screenshare, whereas i thought we had gone back to showing the video separately as it was originally, to avoid occluding the screenshare)

**Comment by robertlong** [comment]
This is fixed on staging now
