### ISSUE TITLE
Set sound output 

### ISSUE THREAD

**Issue by razzeee** [vector-im/matrix-video-chat#151]
**Is your feature request related to a problem? Please describe.**
I would prefer to not have to change the system default output.

Usually I'm working and listening to music on my speakers.
If I need to have a meeting or call, I pause the music and just want my conference app, to know, that I'm going to use the headphones for it.

**Describe the solution you'd like**
Add a setting similar to the input settings, but for output.

**Describe alternatives you've considered**
Not sure, what to suggest here.

**Additional context**
We could cite MS teams handling it as a different setting to the system default too.

**Comment by robertlong** [comment]
Hey @razzeee thanks for filing this. We're already tracking it in #54. Closing this one as a duplicate and you can follow it there.
