### ISSUE TITLE
Update to most recent spotlight layout designs

### ISSUE THREAD

**Issue by robertlong** [vector-im/matrix-video-chat#152]
Most recent designs available here:
https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=636%3A80999

Most pressing issue from @gaelledel:
> On Spotlight layout, the spotlight tile is too small. See example here https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/VoIP-Next-Gen?node-id=265%3A29992

**Comment by heyakyra** [comment]
How do we view those designs? By the way, Penpot is a nice open source alternative to Figma

**Comment by robertlong** [comment]
Hey, sorry these aren't open. I don't know if the designs are published anywhere.

Anyway, this is live now on staging 👍
