### ISSUE TITLE
On the PWL guest, remove the Register action in the drop down

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#159]
On Home screen and Lobby, we shouldn't show a "register"button in the drop down.
If they wish to register, they can do so via the create an account link at bottom left side of Home. They can also do so when a call is ended.
Your impl
<img width="1440" alt="Screenshot 2021-12-17 at 11 55 56" src="https://user-images.githubusercontent.com/76945183/146541416-e3415e19-c361-4133-bdb1-02729f96c74f.png">

Figma
https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=1020%3A94937
<img width="681" alt="Screenshot 2021-12-17 at 11 57 33" src="https://user-images.githubusercontent.com/76945183/146541555-de7ded1e-c09a-4240-b5d3-7d0223591e1f.png">

**Comment by robertlong** [comment]
If I understand this correctly, there will not be a register option in the drop down menu? I've gone ahead and removed it.
