### ISSUE TITLE
Reducing the space Home Left Section

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#162]
Example
<img width="1299" alt="Screenshot 2021-12-17 at 12 17 38" src="https://user-images.githubusercontent.com/76945183/146543791-6020e810-e013-484f-9e96-b7b2c73b4c88.png">
<img width="1298" alt="Screenshot 2021-12-17 at 12 17 51" src="https://user-images.githubusercontent.com/76945183/146543801-c32d64d9-a7a6-44c8-ab01-4d4b93bf1f3a.png">

**Comment by robertlong** [comment]
Ok, I've reduced that padding to 40px. I think what you were asking for is some sort of flexible spacing, but I'd need more info on how you want that to work. This should free up enough space to fit on most screens.
