### ISSUE TITLE
If the app is refreshed while being called, the call may never complete.

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#169]
I believe this is the root cause of the splitbrains which have been plaguing us: if A is in the middle of calling B, and B then refreshes - then A has no way to tell that B has forgotten half the signalling.  Instead, you have to wait 60 seconds for the invite to time out (it looks to A like B is failing to pick up).

Instead, B should re-announce itself to the room when it restarts, and everyone should immediately knife any in-progress calls and try to reconnect to it again.  (B will also be trying to call A, but this may lose thanks to glare if A already thinks it's trying to call B, and A is less than B in the alphabet).

**Comment by robertlong** [comment]
Is this still an issue @ara4n? I feel like we've fixed splitbrains now.

**Comment by robertlong** [comment]
Closing this issue due to lack of recent reports. I think we fixed this.
