### ISSUE TITLE
Name tag VS Mic tag

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#172]
I propose only to show the mic icon and name tag when >1 participant and when the tile is enlarged (double tap). All other tiles should only show the MIC ON/OFF indicator.

https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=1330%3A53468
<img width="288" alt="Screenshot 2022-01-10 at 17 02 57" src="https://user-images.githubusercontent.com/76945183/148807098-5fb53d29-9fdb-4bda-9464-20e289070fd8.png">

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/1d620910c56d3764b607da30b980ba9fc43c1cf7
