### ISSUE TITLE
Avatar issue when changing your name

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#173]
When you change your display name and do not have a photo uploaded, the avatar letter isn't updated and instead a weird thumbnail is displayed
<img width="297" alt="Screenshot 2022-01-11 at 11 01 03" src="https://user-images.githubusercontent.com/76945183/148962493-1ab5300b-5dcb-4f4c-a19c-a1aba21abb97.png">
.

**Comment by robertlong** [comment]
I believe this is fixed now
