### ISSUE TITLE
Audio stutters when running out of CPU

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#176]
In a 7-way full mesh this afternoon, @neilisfragile's Intel Macbook Pro turned into a helicopter and audio was stuttering.
If we can detect this, we should probably start negotiating off remote video for non-speakers (at least until SFUs land).

**Comment by SimonBrandner** [comment]
I wonder if this is related to https://github.com/vector-im/element-web/issues/19294. That issue has the same symptoms for me as this one. I think we just might not be correctly stopping the tracks somehow here

**Comment by robertlong** [comment]
Merging with #199
