### ISSUE TITLE
Lobby CTA Design tweak

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#182]
I have changed the layout for the lobby.
The core CTA is now under the video feed and the "copy link button" is now using white. 

Web
https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=1211%3A53807

Mobile
https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/NG-SPA?node-id=1497%3A54427

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/9c3e4907c8baa21ec123d4fa9df62f7d7eee7962
