### ISSUE TITLE
Splitbrain is still happening where users are entirely missing from conferences

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#183]
During the design syncs, the issue occurred once between Gaelle and Nad and then between Gaelle and Jordan. 
First Jordan's feed froze and I couldn't hear him. His tile then completely disappeared for me when other could still see and hear him. See attached the link to the logs for Jordan and Gaelle. https://drive.google.com/drive/folders/1pYS_2EU4VJ7zX4ZJUwYuQjBxnsYcN0z5

**Comment by robertlong** [comment]
This specific case should be fixed now. Other media issues still at large
