### ISSUE TITLE
Add the ability to create a room directly from the 'room does not exist' error screen.

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#185]
Users may expect to be able to simply send out a URL for a meeting, without explicitely creating it, e.g. matrixvoip.dev/foo
In fact, this will not work unless the room has been explicitely created first by going to the room creation screen and entering foo into the 'create room' dialogue.

This behaviour *is* quite consistent with zoom, for example, but will be odd for users familiar with Jitsi, who don't expect to need to explicitely create a room before using it.

A solution would be to add a button to the 'room does not exist' error screen that allows the user to simply create that room. 

<img width="620" alt="Screenshot 2022-01-26 at 10 23 11" src="https://user-images.githubusercontent.com/87766619/151146356-da36ff84-109f-4714-ad1e-9b9863a899be.png">

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/47357b3fc64afda4b495618f7fba79152fb38c73
