### ISSUE TITLE
Amend HTML title to be more relevant

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#187]
HTML title should be:

Product Name | Room Name

**Comment by NaincyKumariKnoldus** [comment]
Hey @jakewb-b Can I do this please?

**Comment by jakewb-b** [comment]
@NaincyKumariKnoldus absolutely - contributions are always welcome. Thanks!

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/35c11660a3b40c830c3864eab58e27307376253a
