### ISSUE TITLE
Copy inconsistency on call landing page for anonymous user

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#188]
When I land on a call as a non logged-in user, the copy says "By clicking "Go", you agree to our Terms and conditions" but the button says 'Join call now
<img width="414" alt="Screenshot 2022-01-26 at 10 33 06" src="https://user-images.githubusercontent.com/87766619/151147860-af4d5807-dd06-456c-8819-a3dc1164dbfb.png">
'

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/089c891a556e3f341fee583bb5a5afebc1c5d9b4
