### ISSUE TITLE
Match padding above and below avatar in recent calls block

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#189]
Now that we've removed the icons for people in the room, the recent calls block is unbalanced. As a simple fix, Robert, can you just match the padding above and below the avatar in these blocks so it looks even?

**Comment by robertlong** [comment]
<img width="349" alt="Screen Shot 2022-02-04 at 1 00 10 PM" src="https://user-images.githubusercontent.com/1753624/152602400-863f6d87-3a13-41d7-9ef5-7dcf909d6992.png">

Idk that this looks better though. @gaelledel thoughts?

**Comment by gaelledel** [comment]
It's ok - might want to make sure the group of strings is well centred in relation to the avatar and it'll be fine

**Comment by robertlong** [comment]
This is now live
