### ISSUE TITLE
On video feeds, on Chrome, I can right-click and choose 'show all controls'. This creates some odd/breaking behaviour.

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#191]

**Comment by robertlong** [comment]
Not sure what we can do about this short of blocking right click. I don't think we should do this. It's the web and this should be expected. I'd like to mark this as wontfix if that's alright @jakewb-b ?

**Comment by jakewb-b** [comment]
@robertlong yup, I'm happy with that. It's minimally disruptive and it's purely user-caused disruption that they have to make a reasonable amount of effort to trigger.
