### ISSUE TITLE
Camera light (on Mac) does not turn off if you 'mute' your camera in the application.

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#195]
MacBook Pro (13-inch, M1, 2020)
MacOS 11.4

If I press the camera icon in the application to disable my camera, the green light by the camera on my laptop stays on. This should turn off, to give confidence that my camera is not transmitting.

**Comment by SimonBrandner** [comment]
This is an upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=642785

**Comment by robertlong** [comment]
Let's check if this is Chrome specific, because it seems to work in Firefox

**Comment by robertlong** [comment]
Yup, just tested in Chrome on my mac and this is the case. Going to close this and defer to it being fixed upstream.
