### ISSUE TITLE
Scrolling the list of thumbnails when in spotlight mode doesn't follow my setting of 'scroll direction: natural' on my mac

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/matrix-video-chat#200]
I have 'scroll direction: natural' set on my mac, but the list of thumbnails still scrolls in the non-natural direction. Ideally this would pick up the scrolling direction set on the OS?

**Comment by robertlong** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/commit/4606d67a0726a4f79dc0fb972fc838be4d6188ea
