### ISSUE TITLE
Doesn't ask for permissions back after revoking

### ISSUE THREAD

**Issue by babolivier** [vector-im/matrix-video-chat#203]
**Describe the bug**

"Accept webcam/microphone permissions to join the call." is shown but no prompt for permissions.

**To Reproduce**
1. Revoke permission to access the camera
2. Refresh the tab
3. Try to join a call

**Expected behavior**

I'm asked for permission again, like Jitsi does in this scenario.

**Screenshots**

![image](https://user-images.githubusercontent.com/5547783/152815571-a01180ac-3080-4de8-95fc-a2eb751fce11.png)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox
 - Version: 96.0.2

**Additional context**
I sometimes need to revoke permissions to set them again because I have Droidcam installed, which is buggy when my phone isn't connected (but still listed in my video inputs) and since it appears at the top of the list some apps annoyingly end up defaulting to it.

**Comment by robertlong** [comment]
Hmm, I can't reproduce this on my end. When I revoke webcam/microphone permissions and then refresh in Firefox, it always asks for the permissions.

Is this consistently reproducible? Would you mind checking your logs to see if there's an error?
