### ISSUE TITLE
Add a random rageshake_id to rageshakes when triggered from another client.

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/matrix-video-chat#205]
**Is your feature request related to a problem? Please describe.**
When rageshakes are sent, there is no easy way to group the rageshakes if they were requested by a single user.

**Describe the solution you'd like**
https://github.com/vector-im/matrix-video-chat/blob/main/src/settings/rageshake.js#L38
The "body" field should contain a parameter, eg "videochat_rageshake_id" set to a value chosen by the user that created the rageshake request. The value should be emitted in the event created, and other clients that receive the event should write the same rageshake ID into their rageshakes when submitted, so all rageshakes contain the same ID.

**Describe alternatives you've considered**
We could write the github issue created instead, but a random identifier in the event seems easier to setup and manage.

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/4168540017c881a43e4e723ebadf0978f76f1d16
