### ISSUE TITLE
https://matrixvoip.dev/url doesn't auto-create the room

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#208]
**Describe the bug**

Those use to Jitsi expect that https://matrixvoip.dev/foo will automatically create a room called #foo:matrixvoip.dev.

Instead, it errors with "room doesn't exist".  We should autocreate instead.

**Comment by robertlong** [comment]
We should also automatically lowercase these room names and convert invalid characters to a valid room name. So check the url first and then redirect to the correct room. If it doesn't exist, make it so you can create the room.

**Comment by robertlong** [comment]
While we don't auto create the room. We do now let you create the room without breaking the flow inhttps://github.com/vector-im/matrix-video-chat/commit/47357b3fc64afda4b495618f7fba79152fb38c73

**Comment by jakewb-b** [comment]
@robertlong this seems to work nicely for anonymous users, but not for logged in ones - they still get the error message

**Comment by robertlong** [comment]
This should be fixed now. The room not found error is reported differently for unauthenticated users.
