### ISSUE TITLE
Can't join matrixvoip.dev

### ISSUE THREAD

**Issue by deniseal** [vector-im/matrix-video-chat#212]
**Describe the bug**

Tried to join a call on matrixvoip.dev on both Firefox (on macOS, version 95.0.2) and Chrome (also on macOS, version 97.0.4692.99)

**To Reproduce**
 
Copy link [matrixvoip.dev/deniseinez](http://matrixvoip.dev/deniseinez) and paste in browser window. Immediately get an error message (pasted below). Same issue on both browsers

**Expected behavior**
To be able to join a call. 

**Screenshots**

![image](https://user-images.githubusercontent.com/51328716/153578418-af2597fb-1010-4785-9b84-c776140453cd.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Browser Chrome and Firefox (details above)

**Additional context**
Was asked internally if my clock is in sync and can confirm it is.

**Comment by ara4n** [comment]
this is caused by Virgin Media inexplicably breaking DNS for matrixvoip.dev.  It works if you use a different DNS resolver (e.g. 8.8.8.8 or 1.1.1.1)
