### ISSUE TITLE
Ability to tell what version the app is

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#216]
Right now i don't know what commit matrixvoip.dev (or other deployments) are running. Can we surface it in the UI somewhere please?

**Comment by robertlong** [comment]
@dbkr any idea on how best to do this in our Docker setup? Maybe grab the git tag/commit in the build script and assign it to an environment variable?

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/9fc4af2bd7b4093d4bc2e1a2551d0bb8fc78914f
