### ISSUE TITLE
Pulling down on the page refreshes it on iOS

### ISSUE THREAD

**Issue by karlabbott** [vector-im/matrix-video-chat#219]
**Describe the bug**
When you try to rearrange the tiles in freedom mode on iOS, it's too easy to accidentally activate the gesture for "pull to refresh" -- when you refresh, you are kicked out of the call and you have to rejoin.

**To Reproduce**
Go to call.element.io/callslug
Join meeting.
Play with boxes hoping they will move around. 
Accidentally pull a box down, which pulls the page down, which refreshes.

**Expected behavior**
I'm proposing that we disable pull to refresh in the browser while on this page if that is possible. 

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15.3.1
 - Browser: Safari and Brave
 - Version Latest.

**Additional context**
n/a

**Comment by robertlong** [comment]
Looks like we can use `overscroll-behavior: contain;` on Android but not on iOS yet although there's an experimental flag to turn it on. Hopefully that gets turned on soon. In the meantime I'll add this CSS to the in-call view and figure out a hack to fix iOS.

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/0f3a7f9fd996f5961414f00290b8652c27515bf3
