### ISSUE TITLE
Can we turn meeting links into real clickable links please?

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/matrix-video-chat#221]
**Is your feature request related to a problem? Please describe.**
When I copy the link to a call  generated by the app it only gives me call.element.io/mycall which doesn't create a clickable URL if I send it to someone (and is not very non-tech user-proof), so I have to add https:// every time manually.

**Describe the solution you'd like**
Please can the app generate a link which is clickable once pasted into a chat/email/invite

**Describe alternatives you've considered**
-

**Additional context**
![image](https://user-images.githubusercontent.com/8582858/154252431-5326a6fe-6ba6-426c-956c-8c28f4de0ec5.png)

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/1cc634509b617b20f5655ad3b832f92ca05eca48
