### ISSUE TITLE
Remove the green speaking indicator for 1:1 calls

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#224]
It is unnecessary to show the green highlight indicators when on 1:1 calls. can this be disabled and then re enanled when a 3rd person joins?

**Comment by robertlong** [comment]
We've gone back and forth on this before. I think we need some way of knowing if your mic is working. It also helps figure out if the other person is talking. But I do agree it's quite annoying to have the green highlight around the whole tile.

**Comment by robertlong** [comment]
Disabled for now. We may want to revisit this later: https://github.com/vector-im/matrix-video-chat/commit/721cccf152bcd7b1b74c0ab1138c578d355fc5ef
