### ISSUE TITLE
Show an icon explicitly when video is muted

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#225]
When people put themselves on video mute you currently just get their avatar shown instead - it's unclear whether this is because their connectivity or video has crapped out or if they explicitly muted themselves.  We should show an explicit video mute icon if they are muted.

**Comment by robertlong** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/commit/3de122a2d58fc0fe47b96d9cd5f2abaef8b2f2ec
