### ISSUE TITLE
Drop & drag of video tiles in 1:1 mode is super glitchy

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#228]
If you try to reposition your local video preview in 1:1 mode instead it swaps it for the main view, sort of. Either we should disable drop/drag in 1:1 entirely, or let the local video be moved around freestyle.

**Comment by robertlong** [comment]
Yeah, @gaelledel what affordances should we have in the 1:1 Freedom view? Should we disable dragging and just support double tap? Do we need a way to make you the big tile, which is what the drag and drop currently lets you do (although glitches out like crazy).

**Comment by robertlong** [comment]
Fixed by disabling drag in https://github.com/matrix-org/matrix-react-sdk/commit/154576631c9282a1dad8ffa304180a410ebb8287
