### ISSUE TITLE
Creating a call from https://matrixvoip.dev/foo doesn't work

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#230]
If you enter a URL of form https://matrixvoip.dev/wherever then it now prompts you to create the room... but it then crashes after creating the room, and you have to refresh to actually get into the room.

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/641b82dc4544adefb590c9f7b50dbf774fdbcf4c
