### ISSUE TITLE
Display names have username displayed next to them

### ISSUE THREAD

**Issue by robertlong** [vector-im/matrix-video-chat#233]
User submitted bug via rageshake

**Comment by SimonBrandner** [comment]
It could be the case that the js-sdk is trying to do disambiguation

**Comment by robertlong** [comment]
It is, I think we've decided to use the `rawDisplayName` instead in this app.

https://github.com/vector-im/matrix-video-chat/commit/6a18ba0110a19da2b33310fff56d157b33e75e1f
