### ISSUE TITLE
Call Not Found -> Create Room step is unnecessary

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/matrix-video-chat#241]
Today for a 1:1 call, I crafted a new URL (ex. `https://call.element.io/foobarbazasdf`) and sent sent it to the other party. Then I clicked the link myself and pressed `Create Room` which I thought dropped me into the room and I was just waiting for the other party to join (probably assumed by my own camera preview). Then got a message that they were waiting for me 🤦‍♂️. Obviously, reading the UI now, I was on the join room preview screen and needed to click through another screen to actually join the call.

It seems like we could just create the room automatically when visiting the URL and just dump straight into the **Join call now** preview screen.

As a side note, it seems like one the only pieces of UI which refers to the "call" as a "room" instead.

### Reproduction steps

 1. Visit a new URL where the room hasn't been created before, https://call.element.io/foobarbazasdf
 1. `Call Not Found` -> `Create Room` screen
    <img width="415" alt="" src="https://user-images.githubusercontent.com/558581/156061766-556adf45-bd50-4b45-85a8-dc52c0da8e20.png">
 1. `Join call now` preview screen
     <img width="896" alt="" src="https://user-images.githubusercontent.com/558581/156061768-34d84f55-4994-45c7-8eb0-474d1ca971c5.png">

**Comment by robertlong** [comment]
Ok we've agreed to get rid of the interstitial screen. We'll create it automatically.

**Comment by robertlong** [comment]
This is now fixed in https://github.com/vector-im/matrix-video-chat/commit/35fb1e710b2e248b168c92655625e6139048d2fd
