### ISSUE TITLE
Webcam doesn't turn off after leaving call

### ISSUE THREAD

**Issue by robertlong** [vector-im/matrix-video-chat#5]
**Describe the bug**
When leaving the call via navigation, the webcam indicator doesn't turn off.

**To Reproduce**
1. In your mobile or desktop browser, join a call and then click the Element logo in the top right corner.
2. Observe that the webcam indicator is still on

**Expected behavior**
The webcam indicator should turn off.

**Desktop (please complete the following information):**
- Seen in Safari iOS and Desktop Firefox on macOS

**Additional context**
To properly disable the webcam status indicator, all video media stream tracks need to be stopped by calling `.stop()` on them. I thought I was doing this, but that's most likely not the case.

**Comment by SimonBrandner** [comment]
I don't think I am able to reproduce

**Comment by robertlong** [comment]
I've confirmed that this is fixed now. There are multiple browser specific methods for ensuring it is always turned off and they should all be working properly now.
