### ISSUE TITLE
Change Audio Output Device

### ISSUE THREAD

**Issue by robertlong** [vector-im/matrix-video-chat#54]
You should be able to pick which audio output device to use if your browser supports it (Chrome)

**Comment by ara4n** [comment]
For SEO: it's particularly important to have this on iOS (both iPhone & iOS) as otherwise there is no way to engage speakerphone mode.

**Comment by robertlong** [comment]
Fixed in https://github.com/vector-im/matrix-video-chat/commit/2c3ebd4c0332d54ca2704b984b9500cf1c6d004a
