### ISSUE TITLE
UI/ Behaviour tweaks

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#66]
- [ ] #152

- [x] Add tooltips on button hover https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/VoIP-Next-Gen?node-id=546%3A73126

- [x] Make sure participants name tags are always displayed. Currently it only appears on hover.

- [x] Name tag BG transparency should be at 85% https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/VoIP-Next-Gen?node-id=547%3A90151

- [x] Mic states to only show Muted/unmuted states nothing else. Currently we're showing the sound icon??  ( ---> please remove) https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/VoIP-Next-Gen?node-id=547%3A90151

- [x] Mic colours should always be white no matter the state

- [x] Currently if people do not have their camera on, we're showing a camera Off icon as their avatar. As we haven't implemented a profile pic uploader for avatars, could we follow the following rule : ---> If people turn off their camera, we should show an avatar with the first letter of their name and a random colour for background based on the colours used for Names in Element. Example here https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/VoIP-Next-Gen?node-id=547%3A90691  

- [x] Spacing between icons on top right of the UI should be increased to 24px min
<img width="365" alt="Screenshot 2021-10-22 at 12 53 05" src="https://user-images.githubusercontent.com/76945183/138449171-9972541b-3609-4742-b6d1-f315ef946170.png">

- [x] For the layout types, the Gallery icon should be changed to new Freedom icon
<img width="378" alt="Screenshot 2021-10-22 at 12 37 47" src="https://user-images.githubusercontent.com/76945183/138447438-6bf61111-da90-4a8a-821b-79b8e78b9c93.png">

- [x] When people are screen sharing and switch to freedom layout, we don't need a name tag on the tile https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/VoIP-Next-Gen?node-id=533%3A71715. 

- [ ] #153

**Comment by robertlong** [comment]
Split out remaining issues
