### ISSUE TITLE
Splitbrain after exiting and re-entering.

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#81]
I was in a 3-person call via Chrome in a fresh room that i'd created. I quit the browser to enable screen-sharing. I went back in, and could see only one person (a new person who'd joined while i was out). The other 2 users were still there.  I then switched to Safari (as a separate user) and it worked fine.

**Comment by ara4n** [comment]
I then had splitbrain where i was the only person in the room when trying to join on iOS.  It worked on the 3rd attempt though.

**Comment by robertlong** [comment]
I think this might be related to https://github.com/vector-im/matrix-video-chat/issues/84 If the opponent device id wasn't advertised to the other user then it would ignore the invite. I think I've fixed this now and will monitor Sentry over the next week before closing.

**Comment by ara4n** [comment]
I think I saw this earlier while chasing the missing-to-device splitbrain.  For some reason the app logged me out on my iPad, so i logged back in to the same conference.  Half the participants picked up the new device ID and set up calls correctly; the other half didn't, leading to a splitbrain.  There must still be a problem with spotting when new devices join the conf.

**Comment by ara4n** [comment]
pretty sure that we fixed the specific exit/re-enter splitbrain bug by adding session IDs to avoid adjacent sessions colliding.
