### ISSUE TITLE
Stopping screensharing can leave a blank tile in the call

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/matrix-video-chat#87]
**Describe the bug**
A blank gray tile is left in a call after screen sharing is turned off

**To Reproduce**
1. Start screensharing
2. Stop screensharing

**Screenshots**

![Screenshot_20211116_185753](https://user-images.githubusercontent.com/25768714/142046098-585331db-bca0-4e21-b73a-cc4e5b8ae268.png)

**Desktop (please complete the following information):**
 - OS: Debian Bookworm
 - Browser: Chrome
 - Version: 96.0.4664.45

**Comment by robertlong** [comment]
Should be fixed in https://github.com/matrix-org/matrix-js-sdk/commit/5f06df8a878646bd39c023b4258b067000727339 can you verify on your end @SimonBrandner?

**Comment by SimonBrandner** [comment]
Fixed
