### ISSUE TITLE
Stopping screensharing doesn't dismiss the "You're screensharing" pop up

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/matrix-video-chat#88]
**Describe the bug**

The pop up is visible after screen sharing is turned off

**To Reproduce**
1. Start screensharing
2. Stop screensharing

**Screenshots**

![Screenshot_20211116_185753](https://user-images.githubusercontent.com/25768714/142046316-74a42dee-599d-4fe2-ac9b-7e9d86cf51fa.png)

**Desktop (please complete the following information):**
 - OS: Debian Bookworm
 - Browser: Chrome
 - Version: 96.0.4664.45

**Comment by robertlong** [comment]
Likely related to #89

**Comment by robertlong** [comment]
Should be fixed in https://github.com/matrix-org/matrix-js-sdk/commit/5f06df8a878646bd39c023b4258b067000727339 can you verify on your end @SimonBrandner?

**Comment by SimonBrandner** [comment]
Fixed
