### ISSUE TITLE
Can't share screen more than once

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/matrix-video-chat#89]
**Describe the bug**
When trying to screen share a second time I don't get asked what I want to share and a black screen is shared instead.

Could be a `MediaHandler` bug, I guess

**To Reproduce**
1. Start screensharing 
2. Stop screensharing
3. Start screensharing

**Screenshots**
![Screenshot_20211116_185543](https://user-images.githubusercontent.com/25768714/142046606-bb18c511-0025-4a3d-ac7a-fe97e64e4038.png)

**Desktop (please complete the following information):**
 - OS: Debian Bookworm
 - Browser: Chrome
 - Version: 96.0.4664.45

**Comment by robertlong** [comment]
Pretty sure #88 and this issue are related.

**Comment by robertlong** [comment]
Should be fixed in https://github.com/matrix-org/matrix-js-sdk/commit/5f06df8a878646bd39c023b4258b067000727339 can you verify on your end @SimonBrandner?

**Comment by SimonBrandner** [comment]
Fixed
