### ISSUE TITLE
Button to change media devices is very small

### ISSUE THREAD

**Issue by robertlong** [vector-im/matrix-video-chat#98]
The dropdown button for changing camera / microphone is fairly small.

From Foxlet:
> The button to change cameras is *very small*
> It might be easy to miss if you don't already know how to change cameras

**Comment by SimonBrandner** [comment]
I don't think it's necessarily too small, I think the reporter was mainly concerned about switching front/back camera on a phone which should probably have a separate button

**Comment by robertlong** [comment]
@gaelledel any thoughts on how best to address this concern? I agree with Simon that it's particularly bad on mobile.

**Comment by gaelledel** [comment]
Absolutely. My input has been generally focussed on designing for the web platforms but I'll be reviewing mobile soon. 
One question for you though: Is it possible to change button style if we are on Mobile? Just so I know what change needs to be made and where. Cheers!

**Comment by robertlong** [comment]
Yup, we should probably do it based on window size rather than checking explicitly if it's a mobile device, but yeah we can have different styles on smaller screens 👍

**Comment by robertlong** [comment]
The change device model is now added on staging
